version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: orchestrator
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: orchestrator_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://orchestrator:password123@db:5432/orchestrator_db
    volumes:
      - .:/app

volumes:
  postgres_data: 